# Generated by Django 4.2.2 on 2023-07-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_article_old_tags_delete_articletag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
